#Global config file, gets sourced by all game scipts.
#Add environment variables, or even bash logic to modify how all games run.
#Doesn't change your game scripts directly, only gets sourced when you run a game.

#NOTE: ADD 'export' IN FRONT OF ENVIRONMENT VARIABLES.

export PROTONPATH="$BASE_DIR/runners/GE-Proton"     #Change global runner

#export MANGOHUD=1

#export PROTON_ENABLE_HIDRAW=1

#export PROTON_ENABLE_WAYLAND=1

#export PROTON_LOG=1                #Proton log for more in-depth troubleshooting. Writes a LOT, only use when needed. Light log option below
#export PROTON_LOG_DIR="$LOG_DIR"
